[project]
name = "distroscrapper"
version = "1.0.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "graphviz>=0.20.3",
    "httpx>=0.28.1",
    "lxml==5.4.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.13.0",
]
